name: Release on OSSRH and Maven Central

on:
  workflow_dispatch: # Triggered manually for Release

env:
  BUILD_PATH: fr.centralesupelec.edf.riseclipse.developer

jobs:
  call-release-on-ossrh-and-maven-central-workflow:
    name: Release on OSSRH and Maven Central with Maven
    uses: riseclipse/riseclipse-developer/fr.centralesupelec.edf.riseclipse.developer.github/workflows/Release-On-Maven-Central.yml
    with:
      build-path: ${{ env.BUILD_PATH }}
