# *************************************************************************
# **  Copyright (c) 2025 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release snapshots on Central

on:
  push:
    branches:
      - 'develop'

jobs:
  call-release-snapshot-on-central-workflow:
    name: Release snapshots on Maven Central
    uses: ./.github/workflows/Shared-Deploy-Snapshot-Components.yml
    with:
      run_sonarqube: false
    secrets:
      RISECLIPSE_CENTRAL_USERNAME: ${{ secrets.RISECLIPSE_CENTRAL_USERNAME }}
      RISECLIPSE_CENTRAL_PASSWORD: ${{ secrets.RISECLIPSE_CENTRAL_PASSWORD }}
