# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on DockerHub

# This CD workflow releases a Docker version of CLI tool

# Secrets are not passed when calling reusable workflows, so you must pass them from caller
on: 
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REPOSITORY:
        required: true

jobs:
  publish_dockerhub:
    runs-on: ubuntu-latest

    steps: 
    - name: Setup Environment
      run: sudo apt-get install rename

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # NB: Needs to contain a Dockerfile at root of repository
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Pre-Release-and-Prepare-Next-Dev.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts

    - name: Rename folder to avoid errors
      run: |
        cd ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts
        ls
        cd RiseClipseValidatorSCL-*.jar
        ls
        rename 's/.jar//' *.jar
        ls

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ${{ github.workspace }}/${{ github.event.repository.name }}
        push: true
        tags: riseclipse/${{ inputs.DOCKER_REPOSITORY }}:${{ steps.get_version.outputs.project_version }},riseclipse/${{ inputs.DOCKER_REPOSITORY }}:latest
