# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Create pre-release on GitHub

# This CD workflow creates a pre-release on GitHub
# It aslo uploads artifacts if it's a tool

on:
  workflow_call:
    inputs:
      isTool:
        type: boolean
        required: false
        default: false
      release_version:
        type: string
        required: true

jobs:
  pre-release:
    runs-on: ubuntu-latest
    name: Deploy pre-release

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.repository.name }}-${{ inputs.release_version }}
        release_name: ${{ github.event.repository.name }} v${{ inputs.release_version }}
        body: This RiseClipse release contains the latest changes available. You can learn more by reading the documentation.
        draft: false
        prerelease: true

    #################### FOR TOOLS ONLY ####################
    - name: Download artifact
      if: ${{ inputs.isTool }}
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Shared-Prepare-Next-Dev-Tools.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}/artifacts

    - name: Upload binaries to release
      if: ${{ inputs.isTool }}
      uses: AButler/upload-release-assets@v2.0
      with:
        files: ${{ github.workspace }}/artifacts/*.jar;${{ github.workspace }}/artifacts/*.jar/*.jar
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.repository.name }}-${{ inputs.release_version }}
