# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Deploy on RiseClipseWeb

# This CD workflow push the newly released jar to RiseClipseWeb
name: Deploy JAR

on:
  workflow_call:
    inputs:
    dest_folder:
      description: Destination folder on the remote machine
      required: true

env:
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_KEY: ${{ secrets.REMOTE_KEY }}
  REMOTE_PASSPHRASE: ${{ secrets.REMOTE_PASSPHRASE }}
  REMOTE_FOLDER: ${{ secrets.REMOTE_FOLDER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Environment
      run: sudo apt-get install rename

    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Get latest release
      id: latest-release
      run: |
        echo "::set-output name=release-tag::$(curl -Ls https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name)"

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Pre-Release-and-Prepare-Next-Dev.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts
        ref: ${{ steps.latest-release.outputs.release-tag }}

    - name: Rename folder to avoid errors
      run: |
        cd ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts
        rename 's/.jar//' *.jar

    - name: Copy JAR file
      uses: appleboy/scp-action@v1
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ env.REMOTE_KEY }}
        passphrase: ${{ env.REMOTE_PASSPHRASE }}
        source: "*.jar !*Application*"
        target: ${{ env.REMOTE_FOLDER }}/${{ inputs.dest_folder }}
