# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Build

# This CI workflow builds the components or the tool of any RiseClipse repository
# It requires the boolean input <isRiseClipseTool> to know if it has to install P2_to_M2 dependencies first (for RiseClipse tools)
# It is called by the main workflow of the repository

on:
  workflow_call:
    inputs:
      isRiseClipseTool:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}
        ref: ${{ github.ref_name }}

    # Adapted from
    # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven
    - name: Setup Environment
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    #################################### For RiseClipse tools ####################################
    - name: Checkout riseclipse-developper
      uses: actions/checkout@v3
      if: ${{ inputs.isRiseClipseTool }} # Only runs if it's a RiseClipse tool
      with:
        path: riseclipse-developper
        ref: master

    - name: Install P2_to_M2 if RiseClipse tool
      if: ${{ inputs.isRiseClipseTool }} # Only runs if it's a RiseClipse tool
      run: |
        cd riseclipse-developer/fr.centralesupelec.edf.riseclipse.developer.p2_to_m2
        mvn install -U
    #################################### For RiseClipse tools ####################################

    - name: Execute build (maven package)
      run: |
        cd ${{ github.event.repository.name }}
        mvn package -U
