# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on DockerHub

# This CD workflow releases a Docker version of CLI tool

# Secrets are not passed when calling reusable workflows, so you must pass them from caller
on: workflow_call
  secrets:
    DOCKER_USER:
      required: true
      type: string
    DOCKER_PASSWORD:
      required: true
      type: string

jobs:
  publish_dockerhub:
    runs-on: ubuntu-latest

    steps: 
    # NB: Needs to contain a Dockerfile at root of repository
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Prepare-Next-Dev.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}/artifacts

    - name: Rename folder to avoid errors
      run: |
        cd ${{ github.workspace }}/artifacts
        ls
        cd RiseClipseValidatorSCL-*.jar
        ls
        rename 's/.jar//' *.jar

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: alsoares59/riseclipse # USE RISECLIPSE REPOSITORY

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ${{ github.workspace }}/${{ github.event.repository.name }}
        push: true
        tags: alsoares59/${{ github.event.repository.name }}:${{ steps.get_version.outputs.project_version }} # TO BE CHANGED TO RISECLIPSE OWN REPOSITORY
        labels: ${{ steps.meta.outputs.labels }}
