# *************************************************************************
# **  Copyright (c) 2022-24 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on DockerHub

# This CD workflow releases a Docker version of CLI tool

# Secrets are not passed when calling reusable workflows, so you must pass them from caller
on: 
  workflow_call:
    inputs:
      release_version:
        type: string
        required: true
        description: the tag that will be used for the docker image
      docker_repository:
        type: string
        required: true
        description: the name of the docker repository where the image will be put
      release_latest:
        type: boolean
        required: false
        default: true
        description: whether the image should also be tagged with latest
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  publish_dockerhub:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-22.04

    steps: 
    - name: Setup Environment
      run: sudo apt-get install rename

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # NB: Needs to contain a Dockerfile at root of repository
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Pre-Release-and-Prepare-Next-Dev.yml
        workflow_conclusion: success
        path: ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts

    - name: Rename folder to avoid errors
      run: |
        cd ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts
        rename 's/.jar//' *.jar

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with given tag
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}/${{ github.event.repository.name }}
        push: true
        tags: riseclipse/${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.release_version }}

    - name: Build and push Docker image with latest tag
      if: inputs.release_latest
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}/${{ github.event.repository.name }}
        push: true
        tags: riseclipse/${{ inputs.DOCKER_REPOSITORY }}:latest
