# *************************************************************************
# **  Copyright (c) 2022 CentraleSupélec & EDF.
# **  All rights reserved. This program and the accompanying materials
# **  are made available under the terms of the Eclipse Public License v2.0
# **  which accompanies this distribution, and is available at
# **  https://www.eclipse.org/legal/epl-v20.html
# ** 
# **  This file is part of the RiseClipse tool
# **  
# **  Contributors:
# **      Computer Science Department, CentraleSupélec
# **      EDF R&D
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on RiseClipseWeb

# This CD workflow push the newly released jar to RiseClipseWeb

# Secrets are not passed when calling reusable workflows, so you must pass them from caller
on:
  workflow_call:
    inputs:
      dest_folder:
        description: Destination folder on the remote machine
        required: true
      artifact_path:
        type: string
        required: true
      release_version:
        type: string
        required: true
    secrets:
      REMOTE_WEB_HOSTNAME:
        required: true
      REMOTE_WEB_USERNAME:
        required: true
      REMOTE_WEB_PASSWORD:
        required: true
      REMOTE_WEB_FOLDER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Environment
      run: sudo apt-get install rename

    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v2
      with:
        path: ${{ github.event.repository.name }}

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: Pre-Release-and-Prepare-Next-Dev.yml
        workflow_conclusion: success
        path: ${{ inputs.artifact_path }}-${{ inputs.release_version }}.jar

    - name: Rename folder to avoid errors
      run: |
        cd ${{ github.workspace }}/${{ github.event.repository.name }}/artifacts
        rename 's/.jar//' *.jar

    - name: Copy JAR file
      uses: appleboy/scp-action@v1
      with:
        host: ${{ env.REMOTE_WEB_HOSTNAME }}
        username: ${{ env.REMOTE_WEB_USERNAME }}
        password: ${{ env.REMOTE_WEB_PASSWORD }}
        source: "*.jar !*Application*"
        target: ${{ env.REMOTE_WEB_FOLDER }}/${{ inputs.dest_folder }}
